Repository LikeLionHGU/makeup, pull requests merged in 2024-02, with the labels that each got.

#9 feat : 검색 기능 구현
  package-lock.json
  package.json
  src/App.js
  src/header/Header.js
  src/header/Header.module.css
  src/header/image/bell.png
  src/header/image/chat.png
  src/header/image/logo.png
  src/header/image/profile.png
  src/header/search/BoardList.js
  src/header/search/Search.js
  src/header/search/dummydata.json
Labels: feat

#13 feat : 게시판 호버 기능 구현
  img/feed1.png
  src/App.js
  src/banner/Banner.jsx
  src/grid/Grid.js
  src/grid/Grid.jsx
  src/grid/Grid.module.css
  src/grid/data.json
Labels: feat

#20 chore : 경로 변경
  src/header/Header.js
Labels: chore

#21 [feat] : 로그인 기능 구현
  src/App.js
  src/account/LogIn.js
  src/account/SignUp.js
Labels: feat

#24 [style] : 로그인 css 변경
  src/account/LogIn.js
  src/account/LogIn.module.css
  src/account/SignUp.js
  src/account/SignUp.module.css
  src/account/header1.png
Labels: style

#30 feat - 캘린더 날짜 선택 기능 구현
  package-lock.json
  package.json
  src/App.js
  src/calendar/Calendar.jsx
  src/calendar/calendar.module.css
Labels: feat

#32 feat - 시간 예약 기능 구현
  src/calendar/Calendar.jsx
  src/calendar/calendar.module.css
Labels: feat

#34 Hayoung style/#23
  src/write/BoardWrite.js
  src/write/BoardWrite.module.css
  src/write/Group 9.png
  src/write/Post.module.css
Labels: style

#37 style : 캘린더 css
  src/calendar/Calendar.jsx
  src/calendar/calendar.module.css
  src/calendar/img/diary.png
  src/calendar/img/left.png
  src/calendar/img/right.png
Labels: style

#39 feat : 헤더 기능 수정
  src/header/Header.js
  src/header/Header.module.css
  src/header/search/Search.js
Labels: feat

#41 Hayoung style/#36
  src/account/LogIn.js
  src/write/BoardWrite.js
  src/write/BoardWrite.module.css
Labels: style

#43 feat : 게시글 모달창
  src/modal/Modal.module.css
  src/modal/Subtract.png
  src/modal/modal.js
  src/write/BoardWrite.js
Labels: feat

#45 feat : 게시글 입력 창 구현
  src/write/BoardWrite.js
  src/write/BoardWrite.module.css
  src/write/삭제.png
Labels: feat

#47 style : 게시글 여러 스타일 수정
  src/modal/Modal.module.css
  src/write/BoardWrite.js
  src/write/BoardWrite.module.css
Labels: style

#49 style : 게시글 스타일 수정
  src/write/BoardWrite.js
  src/write/BoardWrite.module.css
  src/write/basket.png
  src/write/delete.png
Labels: style

#51 style : 최근 게시물 css 수정
  src/grid/Grid.jsx
  src/grid/Grid.module.css
  src/grid/data.json
  src/grid/heart.png
  src/write/BoardWrite.js
  src/write/BoardWrite.module.css
Labels: style

#53 feat : 캘린더 기능 수정
  package-lock.json
  package.json
  src/App.js
  src/account/LogIn.js
  src/board/Calendar.jsx
  src/calendar/Calendar.tsx
  src/calendar/calendar.module.css
  src/calendar/calendar.module.scss
Labels: feat

#55 style : 게시글 css 수정
  src/write/BoardWrite.module.css
Labels: style

#57 style : 회원가입 css
  src/App.js
  src/account/Complete.jsx
  src/account/Complete.module.css
  src/account/LogIn.js
  src/account/LogIn.module.css
  src/account/Register.jsx
  src/account/Register.module.css
  src/account/SignUp.js
  src/account/SignUp.module.css
  src/account/img/completeicon.png
  src/account/img/emailicon.png
  src/account/img/kakaologo.png
  src/account/img/loginrect.png
  src/account/img/logo.png
  src/account/img/pwicon.png
  src/account/img/signinrect.png
Labels: style

#64 style : 캘린더 데이트피커
  src/App.js
  src/calendar/Calendar.css
  src/calendar/Calendarr.jsx
  src/calendar/Calendarr.module.css
Labels: style

#65 Yeji style/#60
  package-lock.json
  package.json
  public/test.html
  src/Main.css
  src/Main.js
  src/account/LogIn.js
  src/account/SignUp.js
  src/account/SignUp.module.css
  src/banner/Banner.jsx
  src/banner/Slider.jsx
  src/banner/Slider.module.css
  src/banner/img/banner1.png
  src/banner/img/banner2.png
  src/banner/img/banner3.png
  src/header/Header.module.css
  src/header/image/logo.png
Labels: style

#71 style : 멘티 멘토 달력 구분
  src/App.js
  src/calendarMento/MentoCalendar.jsx
  src/grid/Grid.jsx
Labels: style

#72 style : 캘린더 css
  src/calendar/Calendar.css
  src/calendar/Calendarr.module.css
Labels: style

#74 style : 여러가지
  src/banner/Banner.module.css
  src/banner/Slider.jsx
  src/banner/Slider.module.css
  src/calendar/Calendar.css
  src/calendar/Calendarr.module.css
  src/calendar/dummyData.json
  src/grid/Grid.jsx
  src/modal/modal.js
Labels: style

#75 feat : 캘린더 다중 선택 기능 구현
  src/account/Complete.module.css
  src/account/LogIn.js
  src/account/SignUp.js
  src/account/SignUp.module.css
  src/calendar/Calendar.css
  src/calendarMento/MentoCalendar.jsx
  src/calendarMento/MentoCalendar.module.css
  src/calendarMento/calendar.png
Labels: feat

#77 feat : 로그인 / 회원가입 api 연결
  src/account/Complete.jsx
  src/account/LogIn.js
  src/account/LogIn.module.css
  src/account/SignUp.js
  src/account/SignUp.module.css
Labels: feat

#79 feat : 멘티 캘린더 블락 기능
  src/calendar/Calendarr.jsx
  src/calendar/dummyData.json
  src/modal/modal.js
  src/write/BoardWrite.js
  src/write/BoardWrite.module.css
Labels: feat

#81 feat : 로그인, 회원가입 기능 구현
  src/account/LogIn.js
  src/account/LogIn.module.css
  src/account/img/warningicon.png
  src/header/Header.js
  src/header/Header.module.css
  src/header/image/bell.png
  src/header/image/logout.png
  src/header/image/profile.png
  src/write/BoardWrite.js
Labels: feat

#84 feat : 로그인 기능 구현
  src/account/LogIn.js
  src/calendar/Calendarr.jsx
  src/grid/Grid.jsx
  src/header/Header.js
  src/header/Header.module.css
  src/header/image/profile.png
Labels: feat

#86 feat : 캘린더 멘토 api 연결
  src/calendarMento/MentoCalendar.jsx
Labels: feat

#88 Hayoung feat/#83
  src/App.js
  src/calendar/Calendarr.jsx
  src/calendar/Calendarr.module.css
  src/calendarMento/MentoCalendar.jsx
  src/grid/Grid.jsx
  src/uploadPost/UploadPost.jsx
  src/uploadPost/UploadPost.module.css
  src/uploadPost/go.jpg
  src/write/BoardWrite.js
Labels: feat

#90 style : absolute 수정 및 css 수정
  src/calendar/Calendar.css
  src/uploadPost/UploadPost.module.css
  src/write/BoardWrite.js
  src/write/BoardWrite.module.css
Labels: style

#91 style : css 살짝 고치기
  src/App.js
  src/account/LogIn.js
  src/account/LogIn.module.css
  src/account/SignUp.module.css
  src/banner/Slider.jsx
  src/header/search/Search.js
  src/search/SearchBoard.jsx
  src/search/heart.png
  src/search/searchboard.module.css
Labels: style

#93 feat : 로그인 api 연결
  src/account/LogIn.js
  src/account/SignUp.js
  src/calendarMento/MentoCalendar.jsx
Labels: feat

#96 feat : 최근 게시물 피드 수정
  src/App.js
  src/grid/Grid.jsx
  src/uploadPost/UploadPost.jsx
Labels: feat

#98 feat : 캘린더 기능 구현 및 api 연결
  src/calendarMento/MentoCalendar.jsx
  src/header/search/Search.js
  src/search/SearchBoard.jsx
Labels: feat

#100 Hayoung feat/#97
  src/App.js
  src/calendar/Calendarr.jsx
  src/calendarMento/MentoCalendar.jsx
  src/uploadPost/UploadPost.jsx
  src/uploadPost/UploadPost.module.css
  src/write/BoardWrite.js
Labels: feat

#101 feat : 검색 기능 갈작대기
  src/header/search/Search.js
  src/search/SearchBoard.jsx
Labels: feat

#103 feat : 다양한 기능
  src/calendar/Calendarr.jsx
  src/grid/Grid.jsx
  src/modal/modal.js
Labels: feat

#104 feat : css + 검색
  src/header/Header.js
  src/header/Header.module.css
  src/header/image/ehe.png
  src/header/search/Search.js
  src/header/search/Search.module.css
  src/search/SearchBoard.jsx
Labels: feat

#107 style : 글씨체 및 마진값 변경
  src/header/Header.module.css
  src/uploadPost/UploadPost.module.css
Labels: style

#108 style : css
  src/Main.css
  src/calendar/Calendar.css
  src/calendar/Calendarr.jsx
  src/calendar/Calendarr.module.css
Labels: style
